maith_pump_my_gas:
    resource: "@MaithPumpMyGasBundle/Resources/config/routing.yml"
    prefix:   /

maith_common_mailbox:
    resource: "@MaithCommonMailboxBundle/Resources/config/routing.yml"
    prefix:   /

r_santellan_sitio:
    resource: "@RSantellanSitioBundle/Resources/config/routing.yml"
    prefix:   /

maith_common_translator:
    resource: "@MaithCommonTranslatorBundle/Resources/config/routing.yml"
    prefix:   /

maith_common_image:
    resource: "@MaithCommonImageBundle/Resources/config/routing.yml"
    prefix:   /

#maith_common_admin:
#    resource: "@MaithCommonAdminBundle/Resources/config/routing.yml"
#    prefix:   /

#loopita_metalizadora:
#    resource: "@LoopitaMetalizadoraBundle/Resources/config/routing.yml"
#    prefix:   /

maith_common_admin:
    resource: "@MaithCommonAdminBundle/Resources/config/routing.yml"
    prefix:   /

maith_common_users:
    resource: "@MaithCommonUsersBundle/Resources/config/routing.yml"
    prefix:   /

genemu_upload:
    resource: "@GenemuFormBundle/Resources/config/routing/upload.xml"
    
#my_blog_blog:
#    resource: "@MyBlogBlogBundle/Resources/config/routing.yml"
#    prefix:   /

#acme_hello:
#    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
#    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
