RSantellanSitioBundle_admin_blocktags:
    resource: "@RSantellanSitioBundle/Resources/config/routing/complextag.yml"
    prefix:   /admin/blocktags
        
RSantellanSitioBundle_rsproject:
    resource: "@RSantellanSitioBundle/Resources/config/routing/project.yml"
    prefix:   /admin/rsproject

RSantellanSitioBundle_category:
    resource: "@RSantellanSitioBundle/Resources/config/routing/category.yml"
    prefix:   /admin/rscategory


rsantellan_sitio_aboutme:
    pattern:  /{_locale}/aboutme.html
    defaults: { _controller: RSantellanSitioBundle:Default:aboutMe}
    
rsantellan_sitio_contact:
    pattern:  /{_locale}/contact.html
    defaults: { _controller: RSantellanSitioBundle:Default:contact}
    
rsantellan_sitio_projects_show:
    pattern:  /{_locale}/project-{slug}.html
    defaults: { _controller: RSantellanSitioBundle:Default:projectsShow}

rsantellan_sitio_projects_category:
    pattern:  /{_locale}/projects/{slug}.html
    defaults: { _controller: RSantellanSitioBundle:Default:projectsCategory}

rsantellan_sitio_projects:
    pattern:  /{_locale}/projects.html
    defaults: { _controller: RSantellanSitioBundle:Default:projects}  

r_santellan_sitio_homepage:
    pattern:  /
    defaults: { _controller: RSantellanSitioBundle:Default:index }
    
r_santellan_sitio_admin:
    pattern:  /admin
    defaults: { _controller: RSantellanSitioBundle:Default:admin }

