RSantellanSitioBundle_rsproject:
    resource: "@RSantellanSitioBundle/Resources/config/routing/project.yml"
    prefix:   /rsproject

RSantellanSitioBundle_category:
    resource: "@RSantellanSitioBundle/Resources/config/routing/category.yml"
    prefix:   /rscategory

r_santellan_sitio_homepage:
    pattern:  /
    defaults: { _controller: RSantellanSitioBundle:Default:index }
