maith_common_translator_homepage:
    pattern:  /admin/translator.html
    defaults: { _controller: MaithCommonTranslatorBundle:Default:index }
    
maith_common_translator_get_tranlations:
    pattern:  /admin/get-translation.html
    defaults: { _controller: MaithCommonTranslatorBundle:Default:getTranslation }    

maith_common_translator_set_tranlations:
    pattern:  /admin/set-translation.html
    defaults: { _controller: MaithCommonTranslatorBundle:Default:setTranslation }    

maith_common_translator_clear_cache:
    pattern:  /admin/clear-translation.html
    defaults: { _controller: MaithCommonTranslatorBundle:Default:clearTranslationCache }
