parameters:
    admin_translation_bundles:
        - MaithCommonTranslatorBundle
        - MaithCommonAdminBundle
        - MaithCommonImageBundle
#    maith_common_translator.example.class: Maith\Common\TranslatorBundle\Example

services:
#    maith_common_translator.example:
#        class: %maith_common_translator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
