maith_common_mailbox_homepage:
    path:     /mailer/
    defaults: { _controller: MaithCommonMailboxBundle:Default:index }

maith_common_mailbox_list_folder:
    path:     /mailer/list/{folderId}/{pager}
    defaults: { _controller: MaithCommonMailboxBundle:Default:folder, pager: 0 }
    requirements:
        page:  \d+