maith_common_mailbox_homepage:
    path:     /mailer/
    defaults: { _controller: MaithCommonMailboxBundle:Default:index }

maith_common_mailbox_list_folder:
    path:     /mailer/list/{folderId}
    defaults: { _controller: MaithCommonMailboxBundle:Default:folder }