MaithCommonUsersBundle_admin_users:
    resource: "@MaithCommonUsersBundle/Resources/config/routing/user.yml"
    prefix:   /admin/users

maith_common_users_homepage:
    pattern:  /maith/hello/{name}
    defaults: { _controller: MaithCommonUsersBundle:Default:index }
