admin_users:
    pattern:  /
    defaults: { _controller: "MaithCommonUsersBundle:User:index" }

admin_users_show:
    pattern:  /{id}/show
    defaults: { _controller: "MaithCommonUsersBundle:User:show" }

admin_users_new:
    pattern:  /new
    defaults: { _controller: "MaithCommonUsersBundle:User:new" }

admin_users_create:
    pattern:  /create
    defaults: { _controller: "MaithCommonUsersBundle:User:create" }
    requirements: { _method: post }

admin_users_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MaithCommonUsersBundle:User:edit" }

admin_users_update:
    pattern:  /{id}/update
    defaults: { _controller: "MaithCommonUsersBundle:User:update" }
    requirements: { _method: post|put }

admin_users_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MaithCommonUsersBundle:User:delete" }
    requirements: { _method: post|delete }

admin_users_reset_password:
    pattern:  /{id}/resetpassword.html
    defaults: { _controller: "MaithCommonUsersBundle:User:sendChangePasswordEmail" }
