acme_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }

acme_hello_test:
    pattern:  /helloWorld
    defaults: { _controller: AcmeHelloBundle:Default:hello }
