maith_admin_homepage:
    pattern:  /admin
    defaults: { _controller: MaithCommonAdminBundle:Default:index }
    
#maith_admin_media_show:
#    pattern:  /admin/media/{id}/{objectclass}
#    defaults: { _controller: MaithCommonAdminBundle:Albums:retrieveAlbums }    

#

maith_admin_jquery_datatable_langs:
    pattern:  /{_locale}/admin/datatablelang.html
    defaults: { _controller: MaithCommonAdminBundle:Default:retrieveDataTableTexts }  

maith_admin_media_download_file:
    pattern:  /admin/media/download-file/{id}
    defaults: { _controller: MaithCommonAdminBundle:Albums:downloadOriginalFile }

maith_admin_media_update_file_name:
    pattern:  /admin/media/edit-file/{id}
    defaults: { _controller: MaithCommonAdminBundle:Albums:editFileEdition }
    
maith_admin_media_show_file:
    pattern:  /admin/media/show-file/{id}
    defaults: { _controller: MaithCommonAdminBundle:Albums:showFileEdition }
    
maith_admin_media_upload:
    pattern:  /admin/media/upload/{id}
    defaults: { _controller: MaithCommonAdminBundle:Albums:uploadForm }
    
maith_admin_media_actual_upload:
    pattern:  /admin/media/do-upload
    defaults: { _controller: MaithCommonAdminBundle:Albums:doFormUpload }
    
maith_admin_media_refresh_album:
    pattern:  /admin/media/refresh-album.html
    defaults: { _controller: MaithCommonAdminBundle:Albums:refreshAlbum } 
    
maith_admin_media_remove:
    pattern:  /admin/media/remove/{id}
    defaults: { _controller: MaithCommonAdminBundle:Albums:removeFile }
    
maith_admin_media_sort_album:
    pattern:  /admin/media/sort/{id}
    defaults: { _controller: MaithCommonAdminBundle:Albums:sortAlbum }      
    
maith_admin_media_sort_action:
    pattern:  /admin/media/do-album-sort.html
    defaults: { _controller: MaithCommonAdminBundle:Albums:doSortAlbum }
    
maith_admin_media_show_galleries:
    pattern:  /admin/media/galleries.html
    defaults: { _controller: MaithCommonAdminBundle:Albums:showGalleries }         

maith_admin_media_gallery_upload:
    pattern:  /admin/media/gallery/upload/{gallery}
    defaults: { _controller: MaithCommonAdminBundle:Albums:uploadGalleryForm }

maith_admin_media_gallery_actual_upload:
    pattern:  /admin/media/gallery/do-upload
    defaults: { _controller: MaithCommonAdminBundle:Albums:doGalleryFormUpload }

maith_admin_media_gallery_remove:
    pattern:  /admin/media/remove/{gallery}/{file}
    defaults: { _controller: MaithCommonAdminBundle:Albums:removeGalleryFile }
