parameters:
#    maith_common_admin.example.class: Maith\Common\AdminBundle\Example

services:
#    maith_common_admin.example:
#        class: %maith_common_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
