parameters:
#    maith_common_admin.example.class: Maith\Common\AdminBundle\Example

services:
#    maith_common_admin.example:
#        class: %maith_common_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    maith_common_admin.upload:
        class: Maith\Common\AdminBundle\Listener\RequestListener
        arguments: [%maith_common_admin.upload_token%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

    maith_common_admin.twig.maith_m_avatar:
        class: "Maith\Common\AdminBundle\Twig\mAvatarExtension"
        arguments: 
             - "@doctrine.orm.entity_manager"
             - "%kernel.root_dir%"
        tags: 
            -  { name: twig.extension }

    maith_common_delete_listener:
        class: Maith\Common\AdminBundle\Listener\DeleteListener
        tags:
            -  { name: doctrine.event_listener, event: preRemove }
