admin_pump_fueldata:
    path:     /
    defaults: { _controller: "MaithPumpMyGasBundle:FuelData:index" }

admin_pump_fueldata_show:
    path:     /{id}/show
    defaults: { _controller: "MaithPumpMyGasBundle:FuelData:show" }

admin_pump_fueldata_new:
    path:     /new
    defaults: { _controller: "MaithPumpMyGasBundle:FuelData:new" }

admin_pump_fueldata_create:
    path:     /create
    defaults: { _controller: "MaithPumpMyGasBundle:FuelData:create" }
    requirements: { _method: post }

admin_pump_fueldata_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaithPumpMyGasBundle:FuelData:edit" }

admin_pump_fueldata_update:
    path:     /{id}/update
    defaults: { _controller: "MaithPumpMyGasBundle:FuelData:update" }
    requirements: { _method: post|put }

admin_pump_fueldata_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaithPumpMyGasBundle:FuelData:delete" }
    requirements: { _method: post|delete }
