loopita_metalizadora_homepage:
    pattern:  /
    defaults: { _controller: LoopitaMetalizadoraBundle:Default:index }

loopita_metalizadora_servicios:
    pattern:  /servicio/{slug}.html
    defaults: { _controller: LoopitaMetalizadoraBundle:Default:servicios }    
    
loopita_metalizadora_admin:
    pattern:  /admin
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:index }

# Admin Categories    
loopita_metalizadora_category:
    pattern:  /admin/categories.html
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:listCategories }
    
loopita_metalizadora_category_new:
    pattern:  /admin/add-category.html
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:addCategory }    
    
loopita_metalizadora_category_edit:
    pattern:  /admin/edit-category/{id}
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:editCategory }
    
loopita_metalizadora_category_delete:
    pattern:  /admin/delete-category/{id}
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:deleteCategory }
    
loopita_metalizadora_category_order:
    pattern:  /admin/categories-order.html
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:orderCategory }
    
loopita_metalizadora_category_order_save:
    pattern:  /admin/categories-order-save.html
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:saveCategoriesOrder } 
    
loopita_metalizadora_test_upload:
    pattern:  /admin/categories-test-upload.html
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:saveTestUpload }

#Admin project
loopita_metalizadora_projects:
    pattern:  /admin/projects.html
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:listProjects }
    
loopita_metalizadora_project_new:
    pattern:  /admin/add-project.html
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:addProject }    
    
loopita_metalizadora_project_edit:
    pattern:  /admin/edit-project/{id}
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:editProject }    
    
loopita_metalizadora_project_delete:
    pattern:  /admin/delete-project/{id}
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:deleteProject }    