loopita_metalizadora_homepage:
    pattern:  /
    defaults: { _controller: LoopitaMetalizadoraBundle:Default:index }
    
    
loopita_metalizadora_admin:
    pattern:  /admin
    defaults: { _controller: LoopitaMetalizadoraBundle:Admin:index }    