parameters:
#    loopita_metalizadora.example.class: Loopita\MetalizadoraBundle\Example

services:
#    loopita_metalizadora.example:
#        class: %loopita_metalizadora.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
