parameters:
#    my_blog_blog.example.class: MyBlog\BlogBundle\Example

services:
#    my_blog_blog.example:
#        class: %my_blog_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
